[programs.localnet]
solana_anchor_init = "FSqRiRgnHcTVR6Wa3TMKysWdGSMEbhpAiYjTcuQkgATz"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/alexi/.config/solana/anchor-init.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
